[package]
name = "instant-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
mockall = "0.12.1"
open = "5.0.1"
termion = "3.0.0"
toml = "0.5.8"
